import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import Header from './components/client/Header';
import Sidebar from './components/client/Sidebar';
import { SidebarContextProvider } from './contexts/SidebarContext';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <SidebarContextProvider>
                <Content>{children}</Content>
            </SidebarContextProvider>
        </html>
    );
}

function Content({ children }: { children: ReactNode }) {
    return (
        <body className={inter.className}>
            <div className="flex h-screen bg-gray-200">
                <Sidebar />
                <div className="flex flex-col flex-1 overflow-hidden">
                    <Header />
                    <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">{children}</main>
                </div>
            </div>
        </body>
    );
}
